						<div>
							<?php echo $this->vars->helper->get('JsDisplayMessageHelper')
														  ->set('current', true)
														  ->go() ?>
														  
							<div id="editor-block-wrapper-<?php echo $this->vars->uri ?>-<?php echo $this->vars->region ?>-<?php echo $this->vars->key ?>" class="block-wrapper stack">
								<div class="inner-wrap stack">
									<?php echo $this->vars->helper->get('FormFieldErrorHelper')
																  ->set('form', $this->vars->form)
																  ->set('field', 'content')
																  ->go() ?>									
								</div>
								<div class="front-content stack">
									<?php echo $this->vars->block ?>
								</div>	
								<form class="editor-content-wrapper content-form stack" method="<?php echo $this->vars->form->getMethod() ?>" action="<?php echo $this->vars->form->getAction() ?>">
									<textarea class="editor-content" name="content" rows="1" cols="5"></textarea>
									<input type="hidden" name="uri" value="<?php echo $this->vars->uri ?>" />
									<input type="hidden" name="key" value="<?php echo $this->vars->key ?>" />
								</form>
							</div>
<script type="text/javascript">
//<![CDATA[
	$('#editor-block-wrapper-<?php echo $this->vars->uri ?>-<?php echo $this->vars->region ?>-<?php echo $this->vars->key ?>').blockwrapper();
//]]>
</script>
						</div>