			<div class="stack triplet">
				<div id="mascot"></div>
				<div class="triplet-inner">
					<div class="col3">
						<h5><?php echo $this->vars->third_title ?></h5>
						<?php echo $this->vars->third ?>
					</div>
					<div class="col1">
						<?php echo $this->vars->first ?>
					</div>
					<div class="col2">
						<h5><?php echo $this->vars->second_title ?></h5>
						<?php echo $this->vars->second ?>
					</div>
				</div>
			</div>